=== VascoUP/SDIS/Backup/src/assets/metadata.dtd
<!ELEMENT metadata ((storedChunk | backedupChunk )*, diskspace)>

<!ELEMENT storedChunk (fileID)>
<!ELEMENT backedupChunk (fileID, filePath)>
<!ELEMENT diskspace EMPTY>

<!ELEMENT fileID (#PCDATA)>
<!ELEMENT filePath (#PCDATA)>

<!ATTLIST storedChunk chunkID CDATA #REQUIRED>
<!ATTLIST storedChunk size CDATA #REQUIRED>
<!ATTLIST storedChunk prepdeg CDATA #REQUIRED>

<!ATTLIST backedupChunk chunkID CDATA #REQUIRED>
<!ATTLIST backedupChunk serviceID CDATA #REQUIRED>
<!ATTLIST backedupChunk drepdeg CDATA #REQUIRED>
<!ATTLIST backedupChunk prepdeg CDATA #REQUIRED>

<!ATTLIST diskspace size CDATA #REQUIRED>

=== VascoUP/SDIS/FirstSDISProject/src/assets/data.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE metadata SYSTEM "metadata.dtd">
<metadata>
	<!--This is where we store information about the chunks-->
<storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk><storedChunk chunkID="1"><fileID>ea9376ad6bc69f34edc9678de6354c6146861c431f76aed3216f2022c134010a</fileID></storedChunk></metadata>
